const mongoose = require('mongoose');

const mrnSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true },
  mrnId: String,
  company: String,
  mrnsId: String,
  mrnDate: { type: Date },
  projectId:String,
  projectName:String,
  poId: String,
  materialCategory: String,
  materialSubCategory: String,
  materialDescription: String,
  uom: String,
  poQuantity: Number,
  mrnRate: Number,
  mrnAmount: Number,
  mrnQuantity: Number,
  balanceMrn: Number,
  mrnContractorName: String,
  mrnGpName: String,
  // mrnGpId: {type:mongoose.Schema.ObjectId, ref:"GP"},
  invoiceNumber: String,
  invoiceDate: { type: Date },
  transporterName: String,
  grDocumentFileKey: [String], // an array of strings
  grDate: { type: Date },
  vehicleNumber: String,
  ewayBillNumber: String,
  storageLocation: String,
  remark: String,
  vendorName: String,
  vendorId: String,
  vendorAddress: String,
  transportName: String,
  AWB_no: String,
  AWB_DT: String,
  eway_bill_no: String,
  vendorInvoiceNo: String,
  commInvoiceNo: String,
  date: String,
  status: String,
  vehicleNo: String,
  vehicleReleasedAtSite: String,
  vehicleReleasedFromSite: String,
  storage: String,
  ownedGP: String,
  isApproved: { type: Boolean, default: false },
  is_deleted: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

const MRN = mongoose.model('MRN', mrnSchema);

module.exports = MRN;